apiVersion: apps/v1
kind: Deployment
metadata:
  name: moods-api-deployment
  labels:
    component: moods-api
spec:
  replicas: 1
  selector:
    matchLabels:
      component: moods-api
  template:
    metadata:
      labels:
        component: moods-api
    spec:
      containers:
      - name: moods-api
        image: dinezh87/heroviredb14:moods-api-v1
        ports:
        - containerPort: 5002
        env:
          - name: MOODS_SERVICE_ADDR
            value: moods-service-cluster-ip-service:50052
          - name: PORT
            value: "5002"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits: 
            cpu: "500m"
            memory: "512Mi"