apiVersion: v1
kind: ConfigMap
metadata:
  name: gratitude-configmap
data:
  # Database connection properties
  PGUSER: "gratitude_user"
  # PGPASSWORD: "gratitude_password" stored in secrets
  PGHOST: "database-service"
  PGPORT: "5432"
  PGDATABASE: "gratitude"

  # gRPC services
  


  # REST services
  # api-gateway
  ENTRIES_SERVICE_ADDR: "entries-cluster-ip-service:50051"
  OPENAI_MODEL: "gpt-4o-mini"

  # moods-api
  MOODS_SERVICE_ADDR: "moods-service-cluster-ip-service:50052"

  # stats-api
  STATS_SERVICE_ADDR: "stats-service-cluster-ip-service:50053"
  
  # files-service
  S3_BUCKET: "dinesh-b14-gratitude"
  AWS_REGION: "us-east-1"
  S3_PREFIX: ""



