apiVersion: apps/v1
kind: Deployment
metadata:
  name: entries-service-deployment
  labels:
    component: entries-service
spec:
  replicas: 1
  selector:
    matchLabels:
      component: entries-service
  template:
    metadata:
      labels:
        component: entries-service
    spec:
      containers:
      - name: entries-service
        image: dinezh87/heroviredb14:entries-services-v1
        ports:
        - containerPort: 50051
        env:
          - name: PGUSER
            value: admin
          - name: PGHOST
            value: postgres
          - name: PGDATABASE
            value: mydb
          - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
          - name: PGPORT
            value: "5432"
          - name: HOST
            value: "0.0.0.0"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits: 
            cpu: "500m"
            memory: "512Mi"