apiVersion: apps/v1
kind: Deployment
metadata:
  name: moods-service-deployment
  labels:
    component: moods-service
spec:
  replicas: 1
  selector:
    matchLabels:
      component: moods-service
  template:
    metadata:
      labels:
        component: moods-service
    spec:
      containers:
      - name: moods-service
        image: dinezh87/heroviredb14:moods-service-v1
        ports:
        - containerPort: 50052
        env:
          - name: ENTRIES_SERVICE_ADDR
            value: entries-cluster-ip-service:50051
          - name: OPENAI_MODEL
            value: gpt-4o-mini
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits: 
            cpu: "500m"
            memory: "512Mi"