apiVersion: apps/v1
kind: Deployment
metadata:
  name: moods-service-deployment
  labels:
    component: moods-service
spec:
  replicas: 1
  selector:
    matchLabels:
      component: moods-service
  template:
    metadata:
      labels:
        component: moods-service
    spec:
      containers:
      - name: moods-service
        image: dinezh87/heroviredb14:moods-service-v1
        ports:
        - containerPort: 50052
        env:
          - name: PGUSER
            valueFrom:
              configMapKeyRef:
                name: gratitude-configmap
                key: PGUSER
          - name: PGHOST
            valueFrom:
              configMapKeyRef:
                name: gratitude-configmap
                key: PGHOST
          - name: PGDATABASE
            valueFrom:
              configMapKeyRef:
                name: gratitude-configmap
                key: PGDATABASE
          - name: POSTGRES_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: gratitude-secrets
                  key: PGPASSWORD
          - name: PGPORT
            valueFrom:
              configMapKeyRef:
                name: gratitude-configmap
                key: PGPORT
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits: 
            cpu: "500m"
            memory: "512Mi"