apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-service-deployment
  labels:
    component: stats-service
spec:
  replicas: 1
  selector:
    matchLabels:
      component: stats-service
  template:
    metadata:
      labels:
        component: stats-service
    spec:
      containers:
      - name: stats-service
        image: dinezh87/heroviredb14:stats-service-v1
        ports:
        - containerPort: 50053
        env:
          - name: PGUSER
            valueFrom:
              configMapKeyRef:
                name: gratitude-configmap
                key: PGUSER 
          - name: PGHOST
            valueFrom:
              configMapKeyRef:
                name: gratitude-configmap
                key: PGHOST
          - name: PGDATABASE
            valueFrom:
              configMapKeyRef:
                name: gratitude-configmap
                key: PGDATABASE
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: gratitude-secrets
                key: PGPASSWORD
          - name: PGPORT
            valueFrom:  
              configMapKeyRef:
                name: gratitude-configmap
                key: PGPORT
          - name: PORT
            value: "50053"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits: 
            cpu: "500m"
            memory: "512Mi"