apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-main-deployment
  labels:
    component: server-main
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server-main
  template:
    metadata:
      labels:
        component: server-main
    spec:
      containers:
      - name: server-main
        image: dinezh87/heroviredb14:server-main-v1
        ports:
        - containerPort: 5001
        env:
          - name: PGUSER
            value: admin
          - name: PGHOST
            value: postgres
          - name: PGDATABASE
            value: mydb
          - name: POSTGRES_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
          - name: PGPORT
            value: "5432"
          - name: PORT
            value: "5001"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits: 
            cpu: "500m"
            memory: "512Mi"